[package]
name = "geoip-timezone"
version = "0.1.0"
authors = ["Chris Trotman <chris@trotman.io>"]

[dependencies]
chrono = "0.4"
chrono-tz = "0.5"
maxminddb = "0.8.1"
rocket = "0.3.14"
rocket_codegen = "0.3.14"
